apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets
  namespace: crowdsec
automountServiceAccountToken: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-secrets
  namespace: crowdsec
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: crowdsec
    serviceAccount: vault-secrets
    audiences: [vault]
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: lapi
  namespace: crowdsec
spec:
  vaultAuthRef: vault-secrets
  type: kv-v2
  mount: platform
  path: crowdsec/lapi
  refreshAfter: 1h
  destination:
    name: crowdsec-lapi-vault
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: crowdsec-lapi
    - kind: Deployment
      name: crowdsec-appsec
    - kind: DaemonSet
      name: crowdsec-agent
---
# Shared with traefik.
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bouncer
  namespace: crowdsec
spec:
  vaultAuthRef: vault-secrets
  type: kv-v2
  mount: platform
  path: shared/crowdsec-bouncer
  refreshAfter: 1h
  destination:
    name: crowdsec-bouncer-vault
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: crowdsec-lapi
