apiVersion: v1
kind: Namespace
metadata:
  name: payload
  labels:
    pod-security.kubernetes.io/enforce: restricted
    gateway.0xc0.cc/web: "true"
    gateway.0xc0.cc/internal: "true"
    vault.0xc0.cc/apps: "true"
